### ISSUE TITLE
在linux下运行出现exception已找到解决方案

### ISSUE THREAD

**Issue by hongyan0118** [macacajs/macaca-android-docker#6]
下载docker image并且build 之后运行android update sdk --proxy-host mirrors.neusoft.edu.cn --proxy-port 80 -s 出现exception Exception in thread "main" java.lang.UnsatisfiedLinkError: no swt-pi-gtk-3550 or swt-pi-gtk in swt.library.path, java.library.path or the jar file。
加上参数 --no-ui

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android-docker/pull/7
